dry-run: null
hookfiles: null
language: nodejs
sandbox: false
server: 'php app/console --env=test app:fixtures && php app/console --env=test server:run 127.0.0.1:9090'
server-wait: 10
init: false
custom: {}
names: false
only: []
reporter: apiary
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: apiary.apib
endpoint: 'http://localhost:9090'
