# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.service:
        class: AppBundle\Admin\ServiceAdmin
        arguments: [~, AppBundle\Entity\Service, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Service }

    sonata.user.admin.group:
        abstract: true
        public: false
